import type { IpcInvokeChannels, IpcSendChannels, IpcSyncChannels, IpcMainEventChannels } from '../types/ipc'

export const invokeChannels = {
  'mt::ask-for-image-path': true,
  'mt::boot-info-async': true,
  'mt::clipboard::guess-file-path': true,
  'mt::clipboard::read-text': true,
  'mt::cmd::exists': true,
  'mt::fonts::list': true,
  'mt::fs-trash-item': true,
  'mt::fs::copy': true,
  'mt::fs::ensure-dir': true,
  'mt::fs::is-directory': true,
  'mt::fs::is-executable': true,
  'mt::fs::is-file': true,
  'mt::fs::move': true,
  'mt::fs::output-file': true,
  'mt::fs::path-exists': true,
  'mt::fs::read-file': true,
  'mt::fs::readdir': true,
  'mt::fs::stat': true,
  'mt::fs::write-file': true,
  'mt::i18n::is-supported': true,
  'mt::i18n::load': true,
  'mt::i18n::supported': true,
  'mt::keybinding-get-keyboard-info': true,
  'mt::keybinding-get-pref-keybindings': true,
  'mt::keybinding-save-user-keybindings': true,
  'mt::paths::is-image': true,
  'mt::rg::start': true,
  'mt::shell::open-external': true,
  'mt::shell::open-path': true,
  'mt::spellchecker-get-available-dictionaries': true,
  'mt::spellchecker-get-custom-dictionary-words': true,
  'mt::spellchecker-remove-word': true,
  'mt::spellchecker-set-enabled': true,
  'mt::spellchecker-switch-language': true,
  'mt::uploader::upload': true,
  'mt::win::is-fullscreen': true,
  'mt::win::is-maximized': true,
  'update-buffer-state': true,
} satisfies Record<keyof IpcInvokeChannels, boolean>

export const sendChannels = {
  'app-create-editor-window': true,
  'app-create-settings-window': true,
  'app-open-directory-by-id': true,
  'app-open-file-by-id': true,
  'app-open-files-by-id': true,
  'app-open-markdown-by-id': true,
  'broadcast-preferences-changed': true,
  'broadcast-user-data-changed': true,
  'menu-add-recently-used': true,
  'menu-clear-recently-used': true,
  'mt::NEED_UPDATE': true,
  'mt::add-recently-used-document': true,
  'mt::app-try-quit': true,
  'mt::ask-for-image-auto-path': true,
  'mt::ask-for-modify-image-folder-path': true,
  'mt::ask-for-open-project-in-sidebar': true,
  'mt::ask-for-user-data': true,
  'mt::ask-for-user-preference': true,
  'mt::check-for-update': true,
  'mt::clipboard::write-text': true,
  'mt::close-window': true,
  'mt::close-window-confirm': true,
  'mt::cmd-close-window': true,
  'mt::cmd-import-file': true,
  'mt::cmd-new-editor-window': true,
  'mt::cmd-open-file': true,
  'mt::cmd-open-folder': true,
  'mt::cmd-toggle-autosave': true,
  'mt::editor-selection-changed': true,
  'mt::format-link-click': true,
  'mt::get-current-language': true,
  'mt::handle-renderer-error': true,
  'mt::keybinding-debug-dump-keyboard-info': true,
  'mt::make-screenshot': true,
  'mt::menu::popup': true,
  'mt::menu::popup-application': true,
  'mt::open-file': true,
  'mt::open-file-by-window-id': true,
  'mt::open-keybindings-config': true,
  'mt::open-setting-window': true,
  'mt::rename': true,
  'mt::request-keybindings': true,
  'mt::set-editor-format-menus-enabled': true,
  'mt::response-export': true,
  'mt::response-file-move-to': true,
  'mt::response-file-save': true,
  'mt::response-file-save-as': true,
  'mt::response-print': true,
  'mt::rg::cancel': true,
  'mt::save-and-close-tabs': true,
  'mt::save-tabs': true,
  'mt::select-default-directory-to-open': true,
  'mt::set-user-data': true,
  'mt::set-user-preference': true,
  'mt::shell::open-external': true,
  'mt::shell::show-item': true,
  'mt::update-format-menu': true,
  'mt::update-line-ending-menu': true,
  'mt::update-sidebar-menu': true,
  'mt::view-layout-changed': true,
  'mt::win::close': true,
  'mt::win::maximize': true,
  'mt::win::minimize': true,
  'mt::win::set-fullscreen': true,
  'mt::win::toggle-fullscreen': true,
  'mt::win::toggle-maximize': true,
  'mt::win::unmaximize': true,
  'mt::window-add-file-path': true,
  'mt::window-initialized': true,
  'mt::window-tab-closed': true,
  'mt::window-toggle-always-on-top': true,
  'mt::window::drop': true,
  'screen-capture': true,
  'set-image-folder-path': true,
  'set-user-preference': true,
  'watcher-unwatch-all-by-id': true,
  'watcher-unwatch-directory': true,
  'watcher-unwatch-file': true,
  'watcher-watch-directory': true,
  'watcher-watch-file': true,
  'window-add-file-path': true,
  'window-change-file-path': true,
  'window-close-by-id': true,
  'window-file-saved': true,
  'window-reload-by-id': true,
  'window-toggle-always-on-top': true,
} satisfies Record<keyof IpcSendChannels, boolean>

export const syncChannels = {
  'mt::boot-info': true,
  'mt::paths::is-same-sync': true,
} satisfies Record<keyof IpcSyncChannels, boolean>

export const eventChannels = {
  'language-changed': true,
  'mt::UPDATE_AVAILABLE': true,
  'mt::UPDATE_DOWNLOADED': true,
  'mt::UPDATE_ERROR': true,
  'mt::UPDATE_NOT_AVAILABLE': true,
  'mt::about-dialog': true,
  'mt::ask-for-close': true,
  'mt::bootstrap-editor': true,
  'mt::cm-copy-as-html': true,
  'mt::cm-copy-as-rich': true,
  'mt::cm-insert-paragraph': true,
  'mt::cm-paste-as-plain-text': true,
  'mt::current-language': true,
  'mt::editor-ask-file-save': true,
  'mt::editor-ask-file-save-as': true,
  'mt::editor-close-tab': true,
  'mt::editor-edit-action': true,
  'mt::editor-format-action': true,
  'mt::editor-move-file': true,
  'mt::editor-paragraph-action': true,
  'mt::editor-rename-file': true,
  'mt::execute-command-by-id': true,
  'mt::export-success': true,
  'mt::file-saved': true,
  'mt::force-close-tabs-by-id': true,
  'mt::invalidate-image-cache': true,
  'mt::keybindings-response': true,
  'mt::load-state': true,
  'mt::menu::click': true,
  'mt::menu::closed': true,
  'mt::new-untitled-tab': true,
  'mt::open-directory': true,
  'mt::open-new-tab': true,
  'mt::pandoc-not-exists': true,
  'mt::print-service-clearup': true,
  'mt::rg::cancelled': true,
  'mt::rg::done': true,
  'mt::rg::error': true,
  'mt::rg::match': true,
  'mt::rg::progress': true,
  'mt::screenshot-captured': true,
  'mt::set-line-ending': true,
  'mt::set-pathname': true,
  'mt::set-view-layout': true,
  'mt::show-command-palette': true,
  'mt::show-export-dialog': true,
  'mt::show-notification': true,
  'mt::spelling-replace-misspelling': true,
  'mt::spelling-show-switch-language': true,
  'mt::switch-tab-by-file_path': true,
  'mt::switch-tab-by-index': true,
  'mt::tab-save-failure': true,
  'mt::tab-saved': true,
  'mt::tabs-cycle-left': true,
  'mt::tabs-cycle-right': true,
  'mt::toggle-view-layout-entry': true,
  'mt::toggle-view-mode-entry': true,
  'mt::update-file': true,
  'mt::update-object-tree': true,
  'mt::user-preference': true,
  'mt::window-active-status': true,
  'mt::window-enter-full-screen': true,
  'mt::window-leave-full-screen': true,
  'mt::window-maximize': true,
  'mt::window-unmaximize': true,
  'mt::window-zoom': true,
  'settings::change-tab': true,
} satisfies Record<keyof IpcMainEventChannels, boolean>

export function isAllowedChannel(kind: 'invoke' | 'send' | 'sync' | 'event', channel: string): boolean {
  const channels = { invoke: invokeChannels, send: sendChannels, sync: syncChannels, event: eventChannels }[kind]
  if (!Object.hasOwn(channels, channel)) return false
  // The non-mt channels below are main-process EventEmitter messages.
  // They are retained in the historical type contract, never exposed to documents.
  return kind !== 'send' || channel.startsWith('mt::') || channel === 'app-create-editor-window'
}
